### ISSUE TITLE
Cant seem to get it working with Ticker

### ISSUE THREAD

**Issue by vangalvin** [beegee-tokyo/DHTespOrg#4]
I have been building a small heating system that uses a fan and heater driven by a couple of PID routines, monitors the temperature and ideally I wanted to add a humidity sensor. In the system I make use of the Ticker library for updating the temperatures etc.

It seems that using this library in the loop works perfectly but a soon as you try to use it via a ticker the sensor reports nan.. 

`#include <Ticker.h>
#include "DHTesp.h"

Ticker DHTSensor;

#define DHT_PIN D1
bool loopread = true;

DHTesp dht;

void setup() {
  Serial.begin(115200);
  analogWriteFreq(10000); //Set the PWM to 10000 to stop the fan noise.
  dht.setup(DHT_PIN, DHTesp::DHT11); // Connect DHT sensor
  if(!loopread){
      Serial.println("Starting Humiditiy Sensor");
      DHTSensor.attach(2, getDHTData);  //2 second interval to read the sensor
  }
}

void loop() {
if(loopread){
  delay(2000);
  float humidity = dht.getHumidity();
  float temperature = dht.getTemperature();
  Serial.print(dht.getStatusString());
  Serial.print("\t");
  Serial.print(humidity, 1);
  Serial.print("\t\t");
  Serial.print(temperature, 1);
  Serial.print("\t\t");
  Serial.print(dht.toFahrenheit(temperature), 1);
  Serial.print("\t\t");
  Serial.print(dht.computeHeatIndex(temperature, humidity, false), 1);
  Serial.print("\t\t");
  Serial.println(dht.computeHeatIndex(dht.toFahrenheit(temperature), humidity, true), 1);
}
}

void getDHTData(){
//  delay(2000);
  float humidity = dht.getHumidity();
  float temperature = dht.getTemperature();
  Serial.print(dht.getStatusString());
  Serial.print("\t");
  Serial.print(humidity, 1);
  Serial.print("\t\t");
  Serial.print(temperature, 1);
  Serial.print("\t\t");
  Serial.print(dht.toFahrenheit(temperature), 1);
  Serial.print("\t\t");
  Serial.print(dht.computeHeatIndex(temperature, humidity, false), 1);
  Serial.print("\t\t");
  Serial.println(dht.computeHeatIndex(dht.toFahrenheit(temperature), humidity, true), 1);
}`

**Comment by beegee-tokyo** [comment]
That is because the function called by Ticker is a interrupt service routine and there are limitations what you can do there.
Try:
```cpp
#include <Ticker.h>
#include "DHTesp.h"

Ticker DHTSensor;

#define DHT_PIN D1

DHTesp dht;

bool getDHT = false;

void dhtTicker() {
  getDHT = true;
}

void setup() {
  Serial.begin(115200);
  dht.setup(DHT_PIN, DHTesp::DHT11); // Connect DHT sensor
  Serial.println("Starting Humiditiy Sensor");
  DHTSensor.attach(2, dhtTicker); //2 second interval to read the sensor
}

void loop() {
  if (getDHT) {
    getDHTData();
    getDHT = false;
  }
}

void getDHTData(){
  // delay(2000);
  float humidity = dht.getHumidity();
  float temperature = dht.getTemperature();
  Serial.print(dht.getStatusString());
  Serial.print("\t");
  Serial.print(humidity, 1);
  Serial.print("\t\t");
  Serial.print(temperature, 1);
  Serial.print("\t\t");
  Serial.print(dht.toFahrenheit(temperature), 1);
  Serial.print("\t\t");
  Serial.print(dht.computeHeatIndex(temperature, humidity, false), 1);
  Serial.print("\t\t");
  Serial.println(dht.computeHeatIndex(dht.toFahrenheit(temperature), humidity, true), 1);
}
```

**Comment by vangalvin** [comment]
Heck that was a quick response :)
Thanks for that, it seems to be working a treat now thank you, stuck it in the main code and its now reporting back the humidity.  All the rest of the functions seem to be working correctly as well.

Now to clean up the rest of the code and get it ready to be sent to the Antarctic where the student using it can huddle in a nice warm environment and not have to go outside and check on the test chamber.
